version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front-app"
    schedule:
      interval: "weekly"
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"